### ISSUE TITLE
Impliment accessible mode.

### ISSUE THREAD

**Issue by CatsAreCool710** [cqql/alluvium#3]
Hello. I use I3 with a screen reader. I'd like to see if you can add an accessible mode th at shows the window as a normal window, shows the modes as a table, and uses the gtk.accessible widgets. As of now, when I launch it, it shows a popup, does not take any keyboard focus, etc. You can test with orca on linux. This would have to be implimented as a flagt, because this wouldn't end up being an overlay, just to show bindings in a list format.

**Comment by martenlienen** [comment]
Hi, unfortunately, I don't have time at the moment to implement this. But if you end up implementing this yourself, I am open to merge a pull request.
